// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250401104923_StandarizedColumnName")]
    partial class StandarizedColumnName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("backend.Data.Board", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BorderColor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("BorderColors")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CellColor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Cols")
                        .HasColumnType("int");

                    b.Property<string>("DescriptionDown")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DescriptionLeft")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LabelsRight")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LabelsUp")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Rows")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Boards");
                });

            modelBuilder.Entity("backend.Data.Decision", b =>
                {
                    b.Property<int>("DecisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DecisionId"));

                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<int>("DecisionBaseCost")
                        .HasColumnType("int");

                    b.Property<int>("DecisionDeck")
                        .HasColumnType("int");

                    b.Property<string>("DecisionLongDesc")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DecisionShortDesc")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("DecisionId");

                    b.ToTable("Decisions");
                });

            modelBuilder.Entity("backend.Data.DecisionCost", b =>
                {
                    b.Property<int>("DecisionCostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DecisionCostId"));

                    b.Property<int>("DecisionCostWeight")
                        .HasColumnType("int");

                    b.Property<int>("DecisionId")
                        .HasColumnType("int");

                    b.HasKey("DecisionCostId");

                    b.ToTable("DecisionCosts");
                });

            modelBuilder.Entity("backend.Data.DecisionEnabler", b =>
                {
                    b.Property<int>("CardEnablerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CardEnablerId"));

                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<int>("EnablerId")
                        .HasColumnType("int");

                    b.HasKey("CardEnablerId");

                    b.ToTable("DecisionEnablers");
                });

            modelBuilder.Entity("backend.Data.DecisionWeight", b =>
                {
                    b.Property<int>("DecisionWeightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DecisionWeightId"));

                    b.Property<int>("BoosterX")
                        .HasColumnType("int");

                    b.Property<int>("BoosterY")
                        .HasColumnType("int");

                    b.Property<int>("DecisionId")
                        .HasColumnType("int");

                    b.Property<int>("SubboardId")
                        .HasColumnType("int");

                    b.Property<int>("WeightX")
                        .HasColumnType("int");

                    b.Property<int>("WeightY")
                        .HasColumnType("int");

                    b.HasKey("DecisionWeightId");

                    b.ToTable("DecisionWeights");
                });

            modelBuilder.Entity("backend.Data.Feedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("FeedbackId"));

                    b.Property<int>("DecisionId")
                        .HasColumnType("int");

                    b.Property<string>("LongDescription")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("FeedbackId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("backend.Data.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("GameId"));

                    b.Property<int>("BoardId")
                        .HasColumnType("int");

                    b.Property<int>("DecisionDeck")
                        .HasColumnType("int");

                    b.Property<string>("GameDesc")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("GameLongDesc")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("GameId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("backend.Data.GameBoard", b =>
                {
                    b.Property<int>("GameBoardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("GameBoardId"));

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("PozX")
                        .HasColumnType("int");

                    b.Property<int>("PozY")
                        .HasColumnType("int");

                    b.Property<int>("ProcessId")
                        .HasColumnType("int");

                    b.Property<int>("SubboardId")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("GameBoardId");

                    b.ToTable("GameBoards");
                });

            modelBuilder.Entity("backend.Data.GameLog", b =>
                {
                    b.Property<int>("GameLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("GameLogId"));

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DecisionId")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<int>("feedbackId")
                        .HasColumnType("int");

                    b.HasKey("GameLogId");

                    b.ToTable("GameLogs");
                });

            modelBuilder.Entity("backend.Data.GameLogMove", b =>
                {
                    b.Property<int>("GameLogMoveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("GameLogMoveId"));

                    b.Property<int>("BoardId")
                        .HasColumnType("int");

                    b.Property<int>("MoveX")
                        .HasColumnType("int");

                    b.Property<int>("MoveY")
                        .HasColumnType("int");

                    b.Property<int>("ProcessId")
                        .HasColumnType("int");

                    b.Property<int>("SubBoard")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("GameLogMoveId");

                    b.ToTable("GameLogMoves");
                });

            modelBuilder.Entity("backend.Data.GameLogSpec", b =>
                {
                    b.Property<int>("GameLogSpecId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("GameLogSpecId"));

                    b.Property<int>("BoostX")
                        .HasColumnType("int");

                    b.Property<int>("BoostY")
                        .HasColumnType("int");

                    b.Property<int>("GameLogId")
                        .HasColumnType("int");

                    b.Property<int>("MoveX")
                        .HasColumnType("int");

                    b.Property<int>("MoveY")
                        .HasColumnType("int");

                    b.Property<int>("ProcessId")
                        .HasColumnType("int");

                    b.Property<int>("SubboardId")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("GameLogSpecId");

                    b.ToTable("GameLogSpecs");
                });

            modelBuilder.Entity("backend.Data.GameProcess", b =>
                {
                    b.Property<int>("ProcessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProcessId"));

                    b.Property<string>("ProcessDesc")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProcessLongDesc")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ProcessId");

                    b.ToTable("Processes");
                });

            modelBuilder.Entity("backend.Data.Item", b =>
                {
                    b.Property<int>("ItemsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ItemsId"));

                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<string>("HardwareLongDesc")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HardwareShortDesc")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ItemsBaseCost")
                        .HasColumnType("int");

                    b.HasKey("ItemsId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("backend.Data.ItemsCost", b =>
                {
                    b.Property<int>("ItemsCostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ItemsCostId"));

                    b.Property<int>("ItemsCostWeight")
                        .HasColumnType("int");

                    b.Property<int>("ItemsId")
                        .HasColumnType("int");

                    b.HasKey("ItemsCostId");

                    b.ToTable("ItemsCosts");
                });

            modelBuilder.Entity("backend.Data.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TeamId"));

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("TeamBud")
                        .HasColumnType("int");

                    b.Property<string>("TeamLeader")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TeamToken")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("TeamId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("backend.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConfirmationToken")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("LicensesOwned")
                        .HasColumnType("int");

                    b.Property<int>("LicensesUsed")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
