// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250401061942_ChangedGameTokenToTeamToken")]
    partial class ChangedGameTokenToTeamToken
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("backend.Data.Board", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BorderColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BorderColors")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CellColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Cols")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescriptionDown")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionLeft")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LabelsRight")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LabelsUp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rows")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Boards");
                });

            modelBuilder.Entity("backend.Data.Decision", b =>
                {
                    b.Property<int>("DecisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CardId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DecisionBaseCost")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DecisionDeck")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DecisionLongDesc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DecisionShortDesc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DecisionId");

                    b.ToTable("Decisions");
                });

            modelBuilder.Entity("backend.Data.DecisionCost", b =>
                {
                    b.Property<int>("DecisionCostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DecisionCostWeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DecisionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DecisionCostId");

                    b.ToTable("DecisionCosts");
                });

            modelBuilder.Entity("backend.Data.DecisionEnabler", b =>
                {
                    b.Property<int>("CardEnablerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CardId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EnablerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CardEnablerId");

                    b.ToTable("DecisionEnablers");
                });

            modelBuilder.Entity("backend.Data.DecisionWeight", b =>
                {
                    b.Property<int>("DecisionWeightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BoosterX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BoosterY")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DecisionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubboardId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeightX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeightY")
                        .HasColumnType("INTEGER");

                    b.HasKey("DecisionWeightId");

                    b.ToTable("DecisionWeights");
                });

            modelBuilder.Entity("backend.Data.Feedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DecisionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LongDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FeedbackId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("backend.Data.Game", b =>
                {
                    b.Property<int>("Game_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Board_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DecisionDeck")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Game_desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Game_long_desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Game_id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("backend.Data.GameBoard", b =>
                {
                    b.Property<int>("GameBoard_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Game_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Poz_X")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Poz_Y")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Process_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Subboard_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Team_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("GameBoard_id");

                    b.ToTable("GameBoards");
                });

            modelBuilder.Entity("backend.Data.GameLog", b =>
                {
                    b.Property<int>("GameLog_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cost")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<int>("Decision_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Game_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Item_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Team_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("feedback_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("GameLog_id");

                    b.ToTable("GameLogs");
                });

            modelBuilder.Entity("backend.Data.GameLogMove", b =>
                {
                    b.Property<int>("GameLogMove_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Board_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Move_X")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Move_Y")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Process_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sub_board")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Team_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("GameLogMove_id");

                    b.ToTable("GameLogMoves");
                });

            modelBuilder.Entity("backend.Data.GameLogSpec", b =>
                {
                    b.Property<int>("GameLogSpec_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Boost_X")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Boost_Y")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameLog_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Move_X")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Move_Y")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Process_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Subboard_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Team_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("GameLogSpec_id");

                    b.ToTable("GameLogSpecs");
                });

            modelBuilder.Entity("backend.Data.GameProcess", b =>
                {
                    b.Property<int>("Process_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcessLong_desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Process_desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Process_id");

                    b.ToTable("Processes");
                });

            modelBuilder.Entity("backend.Data.Item", b =>
                {
                    b.Property<int>("Items_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Card_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HardwareLongDesc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HardwareShortDesc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemsBaseCost")
                        .HasColumnType("INTEGER");

                    b.HasKey("Items_id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("backend.Data.ItemsCost", b =>
                {
                    b.Property<int>("ItemsCostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemsCostWeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemsCostId");

                    b.ToTable("ItemsCosts");
                });

            modelBuilder.Entity("backend.Data.Team", b =>
                {
                    b.Property<int>("Team_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Game_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Team_Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Team_bud")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Team_leader")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Team_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Team_id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("backend.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConfirmationToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LicensesOwned")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LicensesUsed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
