using backend.Data;

public static class DecisionInitializer {

    public static void Initialize(AppDbContext context) {

        //Dodawanie Decyzji
        var decisions = new List<Decision> {
            new Decision { DecisionId = 1, CardId = 23, DecisionShortDesc = "Stworzenie profilu organizacji", DecisionLongDesc = "Tworzenie profilu digitalizacyjnego przedsiębiorstwa to dynamiczny proces, który wymaga zaangażowania wszystkich szczebli organizacji, od zarządu po pracowników operacyjnych.", DecisionBaseCost = 2, DecisionCostWeight = 1, DeckId = 1 },
            new Decision { DecisionId = 2, CardId = 21, DecisionShortDesc = "Samodzielna inwentaryzacjia poziomu digitalizacji", DecisionLongDesc = "Wsparcie pracowników w zakresie określenia na ile nowoczesne są technologie używane obecnie w firmie, kiedy ostatnio przeprowadziliśmy wymianę i modernizację parku maszynowego, ile w poprzednich latach wydaliśmy na szkolenia i rozwijanie kompetencji naszej załogi.", DecisionBaseCost = 2, DecisionCostWeight = 1, DeckId = 1 },
            new Decision { DecisionId = 3, CardId = 6, DecisionShortDesc = "Analiza konkurencji pod kątem poziomu digitalizacji", DecisionLongDesc = "Analiza konkurencji pod kątem poziomu digitalizacji polega na ocenieniu, w jakim stopniu konkurenci stosują technologie cyfrowe w swoich operacjach.", DecisionBaseCost = 2, DecisionCostWeight = 1, DeckId = 1 },
            new Decision { DecisionId = 4, CardId = 17, DecisionShortDesc = "Ocena kompetencji cyfrowych", DecisionLongDesc = "Przeprowadź ocenę umiejętności cyfrowych pracowników, analizując ich biegłość w korzystaniu z narzędzi cyfrowych oraz gotowość do pracy z nowymi technologiami.", DecisionBaseCost = 2, DecisionCostWeight = 1, DeckId = 1 },
            new Decision { DecisionId = 5, CardId = 22, DecisionShortDesc = "Analiza danych operacyjnych", DecisionLongDesc = "Sprawdź, jak firma zbiera, przetwarza i analizuje dane. Zidentyfikuj, jakie dane są gromadzone, w jaki sposób są przetwarzane i wykorzystywane do podejmowania decyzji.", DecisionBaseCost = 2, DecisionCostWeight = 1, DeckId = 1 },
            new Decision { DecisionId = 6, CardId = 3, DecisionShortDesc = "Określenie kluczowych procesów digitalizacji", DecisionLongDesc = "Proces polegający na analizie działalności organizacji w celu zidentyfikowania obszarów, które mogą zostać ulepszone lub zautomatyzowane za pomocą technologii cyfrowych. Ustal priorytet koncentracji na procesie  na podstawie obecnego stanu digitalizacji. Wybierz maksymalnie 4 procesy.", DecisionBaseCost = 2, DecisionCostWeight = 1, DeckId = 1 },
            new Decision { DecisionId = 7, CardId = 29, DecisionShortDesc = "Ocena procesów wewnętrznych", DecisionLongDesc = "Zidentyfikuj procesy, które mogą być zautomatyzowane lub usprawnione dzięki technologii cyfrowej. Może to obejmować zarządzanie zasobami ludzkimi, łańcuch dostaw, produkcję, sprzedaż, marketing i obsługę klienta.", DecisionBaseCost = 2, DecisionCostWeight = 1, DeckId = 1 },
            new Decision { DecisionId = 8, CardId = 5, DecisionShortDesc = "Stwórz strategię transformacji modelu biznesowego", DecisionLongDesc = "Oceń, czy istnieją możliwości wsparcia modelu biznesowego w technologie cyfrowe, np. sprzedaż online, e-gwarancja, e-instrukcja itp.", DecisionBaseCost = 2, DecisionCostWeight = 1, DeckId = 1 },
            new Decision { DecisionId = 9, CardId = 33, DecisionShortDesc = "Poszukiwanie ambasadorów zmiany wewnątrz organizacji", DecisionLongDesc = "identyfikacja pracowników, którzy mogą odegrać kluczową rolę we wspieraniu i promowaniu transformacji organizacyjnych.", DecisionBaseCost = 2, DecisionCostWeight = 1, DeckId = 1 },
            new Decision { DecisionId = 10, CardId = 8, DecisionShortDesc = "Stworzenie roadmapy digitalizacji", DecisionLongDesc = "Zdefiniuj cele digitalizacji na poziomie operacyjnym i strategicznym. Cele te mogą obejmować zwiększenie efektywności procesów, poprawę obsługi klienta, zmniejszenie kosztów operacyjnych, a także wprowadzenie innowacji produktowych.", DecisionBaseCost = 2, DecisionCostWeight = 1, DeckId = 1 },
            new Decision { DecisionId = 11, CardId = 30, DecisionShortDesc = "Dobór technologii do procesu", DecisionLongDesc = "Wybierz technologie, które najlepiej odpowiadają potrzebom przedsiębiorstwa, takie jak sztuczna inteligencja (AI), Internet Rzeczy (IoT), chmura obliczeniowa, Big Data, automatyzacja procesów (RPA) lub inne.", DecisionBaseCost = 2, DecisionCostWeight = 1, DeckId = 1 },
            new Decision { DecisionId = 12, CardId = 7, DecisionShortDesc = "Testowanie i prototypowanie", DecisionLongDesc = "Zanim nowe technologie zostaną w pełni wdrożone, przetestuj je na mniejszą skalę, aby zminimalizować ryzyko i upewnić się, że spełniają one wymagania firmy.", DecisionBaseCost = 2, DecisionCostWeight = 1, DeckId = 1 },
            new Decision { DecisionId = 13, CardId = 25, DecisionShortDesc = "Małoskalowa integracja systemów", DecisionLongDesc = "Upewnij się, że prototyp rozwiązania jest dobrze zintegrowany z istniejąćymi systemami. Pozwoli to na płynny przepływ danych i efektywne wykorzystanie technologii", DecisionBaseCost = 2, DecisionCostWeight = 1, DeckId = 1 },
            new Decision { DecisionId = 14, CardId = 28, DecisionShortDesc = "Zebranie uwag z instalacji pilotażowej", DecisionLongDesc = "Podczas instalacji pilotażowej kluczowe jest zebranie uwag, które pomogą w dalszej optymalizacji procesu i poprawie działania systemu. W ramach tego etapu zbierane są opinie użytkowników oraz techniczne obserwacje dotyczące funkcjonalności, wydajności i niezawodności instalacji. Uwagi mogą dotyczyć m.in. napotkanych problemów, koniecznych modyfikacji, a także potencjalnych usprawnień. Informacje te stanowią podstawę do wprowadzenia poprawek przed pełnym wdrożeniem, minimalizując ryzyko wystąpienia problemów w przyszłości oraz zwiększając satysfakcję użytkowników końcowych.", DecisionBaseCost = 2, DecisionCostWeight = 1, DeckId = 1 },
            new Decision { DecisionId = 15, CardId = 13, DecisionShortDesc = "Przygotowanie rekomendacji do wdrożenia", DecisionLongDesc = "Obejmuje analizę zebranych danych, ocenę wyników testów oraz identyfikację kluczowych obszarów wymagających zmian lub optymalizacji. Na podstawie tych informacji tworzone są zalecenia dotyczące dalszych działań, w tym modyfikacji technicznych, zmian procesowych oraz strategii wdrożeniowej. Celem rekomendacji jest zapewnienie płynnego i efektywnego wdrożenia, minimalizowanie ryzyka, oraz maksymalizacja korzyści płynących z nowego rozwiązania. Dokument z rekomendacjami stanowi podstawę do podejmowania decyzji przez zespół wdrożeniowy i kierownictwo projektu.", DecisionBaseCost = 2, DecisionCostWeight = 1, DeckId = 1 },
            new Decision { DecisionId = 16, CardId = 20, DecisionShortDesc = "Analiza potrzeb szkoleniowych - ocena umiejętności", DecisionLongDesc = "Przed rozpoczęciem szkoleń należy przeprowadzić dokładną analizę kompetencji pracowników. Celem jest zidentyfikowanie braków w wiedzy i umiejętnościach cyfrowych, które mogą przeszkodzić w skutecznej adaptacji nowych technologii.", DecisionBaseCost = 2, DecisionCostWeight = 1, DeckId = 1 },
            new Decision { DecisionId = 17, CardId = 11, DecisionShortDesc = "Opracuj indywidualne ścieżki rozwoju", DecisionLongDesc = "Nie wszyscy pracownicy potrzebują tych samych szkoleń. W zależności od ról i odpowiedzialności, szkolenia powinny być dostosowane do indywidualnych potrzeb zespołów, np. dla działów IT, marketingu, produkcji czy HR.", DecisionBaseCost = 2, DecisionCostWeight = 1, DeckId = 1 },
            new Decision { DecisionId = 18, CardId = 31, DecisionShortDesc = "Przeprowadź szkolenie techniczne", DecisionLongDesc = "Obejmują naukę obsługi nowych narzędzi, systemów oraz technologii. Mogą to być szkolenia dotyczące nowych platform ERP, systemów zarządzania projektami, rozwiązań chmurowych, czy zaawansowanych narzędzi analitycznych (np. Big Data, AI).", DecisionBaseCost = 2, DecisionCostWeight = 1, DeckId = 1 },
            new Decision { DecisionId = 19, CardId = 18, DecisionShortDesc = "Przeprowadź szkolenie z zakresu cyberbezpieczeńśtwa", DecisionLongDesc = "Digitalizacja zwiększa ryzyko związane z cyberatakami. Ważnym elementem szkolenia pracowników jest edukacja na temat bezpieczeństwa danych, wykrywania zagrożeń oraz zasad ochrony informacji.", DecisionBaseCost = 2, DecisionCostWeight = 1, DeckId = 1 },
            new Decision { DecisionId = 20, CardId = 26, DecisionShortDesc = "Przeprowadź szkolenie z zakresu zarządzania zmianą", DecisionLongDesc = "Pracownicy, szczególnie menedżerowie, powinni być przygotowani do zarządzania procesem zmian, w tym komunikacją z zespołem, motywowaniem pracowników oraz radzeniem sobie z oporem wobec nowych technologii.", DecisionBaseCost = 2, DecisionCostWeight = 1, DeckId = 1 },
            new Decision { DecisionId = 21, CardId = 15, DecisionShortDesc = "Przeprowadź szkolenie z kompetencji miękkich", DecisionLongDesc = "Transformacja cyfrowa wymaga często zmiany stylu pracy i komunikacji. Szkolenia miękkie mogą obejmować naukę efektywnej współpracy w zespołach zdalnych, zarządzanie czasem, a także rozwijanie kreatywności i innowacyjności.", DecisionBaseCost = 2, DecisionCostWeight = 1, DeckId = 1 },
            new Decision { DecisionId = 22, CardId = 4, DecisionShortDesc = "Ocena efektywności szkoleń", DecisionLongDesc = "Po zakończeniu szkoleń warto przeprowadzać testy wiedzy lub certyfikacje, aby upewnić się, że pracownicy opanowali niezbędne umiejętności. Dodatkowo regularne zbieranie opinii od uczestników szkoleń pozwala na bieżąco dostosowywać programy szkoleniowe i reagować na ewentualne braki w edukacji.Należy też pamiętać, że wdrażanie technologii i szkoleń powinno być monitorowane poprzez ocenę postępów pracowników w codziennej pracy oraz ich adaptacji do nowych narzędzi.", DecisionBaseCost = 2, DecisionCostWeight = 1, DeckId = 1 },
            new Decision { DecisionId = 23, CardId = 1, DecisionShortDesc = "Stworzenie szczegółowego planu wdrożenia", DecisionLongDesc = "Kluczowy krok w realizacji projektu, który zapewnia płynne przejście od etapu planowania do realizacji", DecisionBaseCost = 2, DecisionCostWeight = 1, DeckId = 1 },
            new Decision { DecisionId = 24, CardId = 10, DecisionShortDesc = "Przygotowanie budżetu i zasobów", DecisionLongDesc = "Określ potrzebne zasoby ludzkie, technologiczne i finansowe. Upewnij się, że firma ma odpowiedni budżet na wdrożenie technologii, w tym na ewentualne nieprzewidziane koszty.", DecisionBaseCost = 2, DecisionCostWeight = 1, DeckId = 1 },
            new Decision { DecisionId = 25, CardId = 16, DecisionShortDesc = "Przygotowanie zespołu", DecisionLongDesc = "Kluczowe jest informowanie zespołów o planach wdrożenia, celach i korzyściach wynikających z nowej technologii. Przejrzysta komunikacja pomoże zminimalizować opór i zwiększy zaangażowanie pracowników.", DecisionBaseCost = 2, DecisionCostWeight = 1, DeckId = 1 },
            new Decision { DecisionId = 26, CardId = 9, DecisionShortDesc = "Przeprowadzenie szkoleń", DecisionLongDesc = " Przed pełnym wdrożeniem należy zapewnić pracownikom odpowiednie szkolenia, które pomogą im opanować nowe narzędzia i technologie. Warto również przeprowadzić dodatkowe sesje szkoleniowe dla menedżerów, aby zapewnić im umiejętności niezbędne do zarządzania zespołami w nowym cyfrowym środowisku.", DecisionBaseCost = 2, DecisionCostWeight = 1, DeckId = 1 },
            new Decision { DecisionId = 27, CardId = 32, DecisionShortDesc = "Przeprowadzenie testów końcowych", DecisionLongDesc = "Przed pełnym wdrożeniem przeprowadź końcowe testy technologii w rzeczywistych warunkach operacyjnych. Testy powinny obejmować różne scenariusze działania, w tym obciążenia systemów, aby upewnić się, że są one w stanie obsłużyć pełne wdrożenie.", DecisionBaseCost = 2, DecisionCostWeight = 1, DeckId = 1 },
            new Decision { DecisionId = 28, CardId = 19, DecisionShortDesc = "Zbieranie feedbacku", DecisionLongDesc = "Zbieranie informacji zwrotnych: Nawet po pełnym wdrożeniu warto regularnie zbierać opinie od pracowników oraz klientów na temat funkcjonowania technologii. Feedback jest cenny dla dalszego doskonalenia procesów i dostosowania technologii do zmieniających się potrzeb.", DecisionBaseCost = 2, DecisionCostWeight = 1, DeckId = 1 },
            new Decision { DecisionId = 29, CardId = 27, DecisionShortDesc = "Iteracyjne doskonalenie", DecisionLongDesc = "Proces wdrożenia technologii nie kończy się po jej pełnym zastosowaniu. W miarę zdobywania nowych doświadczeń i informacji można wprowadzać dalsze poprawki i optymalizacje, co pozwala na długoterminowe usprawnienia", DecisionBaseCost = 2, DecisionCostWeight = 1, DeckId = 1 },
            new Decision { DecisionId = 30, CardId = 12, DecisionShortDesc = "Monitorowanie bezpieczeństwa", DecisionLongDesc = "Zwiększona digitalizacja i skalowanie technologii wymagają stałego monitorowania bezpieczeństwa danych i systemów. Należy regularnie przeglądać polityki bezpieczeństwa, testować systemy i reagować na nowe zagrożenia.", DecisionBaseCost = 2, DecisionCostWeight = 1, DeckId = 1 },
            new Decision { DecisionId = 31, CardId = 2, DecisionShortDesc = "Zarządzanie danymi", DecisionLongDesc = "W miarę skalowania technologii rośnie znaczenie zarządzania danymi. Warto zainwestować w narzędzia do analizy danych, które pozwolą na lepsze wykorzystanie zasobów informacyjnych oraz podejmowanie decyzji opartych na danych.", DecisionBaseCost = 2, DecisionCostWeight = 1, DeckId = 1 },
            new Decision { DecisionId = 32, CardId = 14, DecisionShortDesc = "Rozwój technologii", DecisionLongDesc = "Skalowanie wdrożonej technologii to także okazja do dalszego rozwoju i dodawania nowych funkcjonalności. W miarę jak firma zdobywa doświadczenie z nową technologią, można wprowadzać kolejne innowacje, które będą jeszcze bardziej usprawniać procesy.", DecisionBaseCost = 2, DecisionCostWeight = 1, DeckId = 1 },
            new Decision { DecisionId = 33, CardId = 36, DecisionShortDesc = "Integracja z nowymi technologiami:", DecisionLongDesc = "Przedsiębiorstwo powinno być otwarte na integrację istniejących technologii z nowymi, które mogą pojawić się na rynku. To umożliwia firmie ciągłe pozostawanie na czele innowacji oraz dostosowywanie się do dynamicznych zmian technologicznych.", DecisionBaseCost = 2, DecisionCostWeight = 1, DeckId = 1 },
            new Decision { DecisionId = 34, CardId = 35, DecisionShortDesc = "Budowanie kultury innowacyjności", DecisionLongDesc = "Promowanie kultury innowacyjności w organizacji jest kluczowe, aby zachęcać pracowników do poszukiwania nowych rozwiązań technologicznych oraz usprawnień. Tworzenie zespołów innowacyjnych lub laboratoriów innowacji może wspierać dalszy rozwój przedsiębiorstwa.", DecisionBaseCost = 2, DecisionCostWeight = 1, DeckId = 1 },
            new Decision { DecisionId = 35, CardId = 34, DecisionShortDesc = "Kontynuacja edukacji.", DecisionLongDesc = "Utrzymanie procesu edukacyjnego i rozwój kompetencji pracowników w zakresie nowych technologii pozostaje istotnym elementem długoterminowego sukcesu digitalizacji.", DecisionBaseCost = 2, DecisionCostWeight = 1, DeckId = 1 },
            new Decision { DecisionId = 36, CardId = 24, DecisionShortDesc = "Stworzenie spójnego ekosystemu firmy", DecisionLongDesc = " to kluczowy element skutecznej transformacji cyfrowej. Ekosystem firmy to zintegrowana sieć narzędzi, technologii, procesów i relacji, które razem wspierają działalność operacyjną, umożliwiając firmie efektywnie realizować swoje cele. W dobrze zbudowanym ekosystemie każda jego część działa w harmonii z pozostałymi, co pozwala na płynne funkcjonowanie organizacji i szybkie reagowanie na zmiany rynkowe.", DecisionBaseCost = 2, DecisionCostWeight = 1, DeckId = 1 },
            new Decision { DecisionId = 37, CardId = 38, DecisionShortDesc = "Powołanie zespołu ds. digitalizacjoi", DecisionLongDesc = "Zidentyfikuj potrzeby digitalizacji, wybierz odpowiednich członków zespołu, zdefiniuj cele i strukturę organizacyjną, a następnie opracuj plan działania.", DecisionBaseCost = 2, DecisionCostWeight = 1, DeckId = 1 },
            new Decision { DecisionId = 38, CardId = 37, DecisionShortDesc = "Stworzenie zespołu wdrożeniowego", DecisionLongDesc = "Wybierz kluczowych pracowników, określ ich role i odpowiedzialności, zdefiniuj cele wdrożenia i harmonogram działań, a następnie opracuj plan realizacji projektu.", DecisionBaseCost = 2, DecisionCostWeight = 1, DeckId = 1 },
        };

        foreach (var newDecision in decisions)
        {
            var existingDecision = context.Decisions.FirstOrDefault(d => d.CardId == newDecision.CardId);
            if (existingDecision != null)
            {
                
                // Aktualizacja danych użytkownika
                existingDecision.DecisionId = newDecision.DecisionId;
                existingDecision.CardId = newDecision.CardId;
                existingDecision.DecisionShortDesc = newDecision.DecisionShortDesc;
                existingDecision.DecisionLongDesc = newDecision.DecisionLongDesc;
                existingDecision.DecisionBaseCost = newDecision.DecisionBaseCost;
                existingDecision.DeckId = newDecision.DeckId;
            }
            else
            {
                // Dodanie nowego użytkownika
                context.Decisions.Add(newDecision);
            }
        }
        context.SaveChanges();
        Console.WriteLine("Zaktualizowano / dodano Decyzje do bazy MySQL!");
    }
}