using backend.Data;

public static class DecisionEnablerInitializer {

    public static void Initialize(AppDbContext context) {

        //Dodawanie Decyzji
        var de = new List<DecisionEnabler> {
            new DecisionEnabler { DecisionEnablerId = 1, CardId = 1, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 2, CardId = 2, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 3, CardId = 3, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 4, CardId = 4, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 5, CardId = 5, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 6, CardId = 6, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 7, CardId = 7, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 8, CardId = 8, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 9, CardId = 8, EnablerId = 16 },
            new DecisionEnabler { DecisionEnablerId = 10, CardId = 9, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 11, CardId = 10, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 12, CardId = 11, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 13, CardId = 11, EnablerId = 17 },
            new DecisionEnabler { DecisionEnablerId = 14, CardId = 11, EnablerId = 20 },
            new DecisionEnabler { DecisionEnablerId = 15, CardId = 12, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 16, CardId = 13, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 17, CardId = 13, EnablerId = 10 },
            new DecisionEnabler { DecisionEnablerId = 18, CardId = 13, EnablerId = 37 },
            new DecisionEnabler { DecisionEnablerId = 19, CardId = 13, EnablerId = 38 },
            new DecisionEnabler { DecisionEnablerId = 20, CardId = 13, EnablerId = 28 },
            new DecisionEnabler { DecisionEnablerId = 21, CardId = 14, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 22, CardId = 15, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 23, CardId = 16, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 24, CardId = 17, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 25, CardId = 18, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 26, CardId = 19, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 27, CardId = 19, EnablerId = 32 },
            new DecisionEnabler { DecisionEnablerId = 28, CardId = 19, EnablerId = 13 },
            new DecisionEnabler { DecisionEnablerId = 29, CardId = 20, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 30, CardId = 21, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 31, CardId = 22, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 32, CardId = 23, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 33, CardId = 24, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 34, CardId = 24, EnablerId = 13 },
            new DecisionEnabler { DecisionEnablerId = 35, CardId = 24, EnablerId = 35 },
            new DecisionEnabler { DecisionEnablerId = 36, CardId = 24, EnablerId = 27 },
            new DecisionEnabler { DecisionEnablerId = 37, CardId = 25, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 38, CardId = 26, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 39, CardId = 27, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 40, CardId = 27, EnablerId = 13 },
            new DecisionEnabler { DecisionEnablerId = 41, CardId = 28, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 42, CardId = 29, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 43, CardId = 30, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 44, CardId = 31, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 45, CardId = 32, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 46, CardId = 32, EnablerId = 13 },
            new DecisionEnabler { DecisionEnablerId = 47, CardId = 33, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 48, CardId = 34, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 49, CardId = 35, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 50, CardId = 35, EnablerId = 13 },
            new DecisionEnabler { DecisionEnablerId = 51, CardId = 36, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 52, CardId = 37, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 53, CardId = 100, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 54, CardId = 101, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 55, CardId = 102, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 56, CardId = 103, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 57, CardId = 104, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 58, CardId = 105, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 59, CardId = 106, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 60, CardId = 107, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 61, CardId = 108, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 62, CardId = 109, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 63, CardId = 110, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 64, CardId = 111, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 65, CardId = 112, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 66, CardId = 201, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 67, CardId = 202, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 68, CardId = 203, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 69, CardId = 204, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 70, CardId = 205, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 71, CardId = 206, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 72, CardId = 207, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 73, CardId = 208, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 74, CardId = 209, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 75, CardId = 210, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 76, CardId = 211, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 77, CardId = 212, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 78, CardId = 213, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 79, CardId = 214, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 80, CardId = 215, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 81, CardId = 216, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 82, CardId = 217, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 83, CardId = 218, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 84, CardId = 219, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 85, CardId = 220, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 86, CardId = 221, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 87, CardId = 222, EnablerId = 23 },
            new DecisionEnabler { DecisionEnablerId = 88, CardId = 100, EnablerId = 13 },
            new DecisionEnabler { DecisionEnablerId = 89, CardId = 101, EnablerId = 13 },
            new DecisionEnabler { DecisionEnablerId = 90, CardId = 102, EnablerId = 13 },
            new DecisionEnabler { DecisionEnablerId = 91, CardId = 103, EnablerId = 13 },
            new DecisionEnabler { DecisionEnablerId = 92, CardId = 104, EnablerId = 13 },
            new DecisionEnabler { DecisionEnablerId = 93, CardId = 105, EnablerId = 13 },
            new DecisionEnabler { DecisionEnablerId = 94, CardId = 106, EnablerId = 13 },
            new DecisionEnabler { DecisionEnablerId = 95, CardId = 107, EnablerId = 13 },
            new DecisionEnabler { DecisionEnablerId = 96, CardId = 108, EnablerId = 13 },
            new DecisionEnabler { DecisionEnablerId = 97, CardId = 109, EnablerId = 13 },
            new DecisionEnabler { DecisionEnablerId = 98, CardId = 110, EnablerId = 13 },
            new DecisionEnabler { DecisionEnablerId = 99, CardId = 111, EnablerId = 13 },
            new DecisionEnabler { DecisionEnablerId = 100, CardId = 112, EnablerId = 13 },
            new DecisionEnabler { DecisionEnablerId = 101, CardId = 201, EnablerId = 13 },
            new DecisionEnabler { DecisionEnablerId = 102, CardId = 202, EnablerId = 13 },
            new DecisionEnabler { DecisionEnablerId = 103, CardId = 203, EnablerId = 13 },
            new DecisionEnabler { DecisionEnablerId = 104, CardId = 204, EnablerId = 13 },
            new DecisionEnabler { DecisionEnablerId = 105, CardId = 205, EnablerId = 13 },
            new DecisionEnabler { DecisionEnablerId = 106, CardId = 206, EnablerId = 13 },
            new DecisionEnabler { DecisionEnablerId = 107, CardId = 207, EnablerId = 13 },
            new DecisionEnabler { DecisionEnablerId = 108, CardId = 208, EnablerId = 13 },
            new DecisionEnabler { DecisionEnablerId = 109, CardId = 209, EnablerId = 13 },
            new DecisionEnabler { DecisionEnablerId = 110, CardId = 210, EnablerId = 13 },
            new DecisionEnabler { DecisionEnablerId = 111, CardId = 211, EnablerId = 13 },
            new DecisionEnabler { DecisionEnablerId = 112, CardId = 212, EnablerId = 13 },
            new DecisionEnabler { DecisionEnablerId = 113, CardId = 213, EnablerId = 13 },
            new DecisionEnabler { DecisionEnablerId = 114, CardId = 214, EnablerId = 13 },
            new DecisionEnabler { DecisionEnablerId = 115, CardId = 215, EnablerId = 13 },
            new DecisionEnabler { DecisionEnablerId = 116, CardId = 216, EnablerId = 13 },
            new DecisionEnabler { DecisionEnablerId = 117, CardId = 217, EnablerId = 13 },
            new DecisionEnabler { DecisionEnablerId = 118, CardId = 218, EnablerId = 13 },
            new DecisionEnabler { DecisionEnablerId = 119, CardId = 219, EnablerId = 13 },
            new DecisionEnabler { DecisionEnablerId = 120, CardId = 220, EnablerId = 13 },
            new DecisionEnabler { DecisionEnablerId = 121, CardId = 221, EnablerId = 13 },
            new DecisionEnabler { DecisionEnablerId = 122, CardId = 222, EnablerId = 13 },
        };

        foreach (var newDE in de)
        {
            bool cardExists = context.Cards
                .Any(c => c.CardId == newDE.CardId
                );
            if (!cardExists)
                continue;

            bool alreadySeeded = context.DecisionEnablers
                .Any(de => de.DecisionEnablerId == newDE.DecisionEnablerId);
            if (alreadySeeded)
                continue;

            context.DecisionEnablers.Add(newDE);
        }
        context.SaveChanges();
        Console.WriteLine("Zaktualizowano / dodano Talie do bazy MySQL!");
    }
}