
using backend.Data;


public static class ItemInitializer {

    public static void Initialize(AppDbContext context){
        
        // Dodawanie Przedmiotów
        var items = new List<Item>
        {
            new Item {DeckId = 1, ItemsId = 1, HardwareShortDesc = "Sterowniki PLC", HardwareLongDesc = "PLC to programowalne urządzenia, które sterują maszynami i procesami przemysłowymi. Są kluczowe dla automatyzacji produkcji, pozwalają na monitorowanie i kontrolę operacji w czasie rzeczywistym.Zastosowanie: Sterowanie liniami produkcyjnymi, maszynami, robotami przemysłowymi, systemami transportu materiałów.", ItemsBaseCost = 0.5, ItemsCostWeight = 1 },
            new Item {DeckId = 1, ItemsId = 2, HardwareShortDesc = "HMI (Human-Machine Interface)", HardwareLongDesc = "Interfejsy człowiek-maszyna (HMI) umożliwiają operatorom interakcję z systemami kontrolnymi w hali produkcyjnej. HMI wyświetlają dane produkcyjne, stan maszyn oraz umożliwiają ręczne sterowanie i monitorowanie procesów.Zastosowanie: Monitorowanie i kontrolowanie maszyn, dostęp do danych w czasie rzeczywistym, alarmowanie o problemach.", ItemsBaseCost = 0.5, ItemsCostWeight = 1 },
            new Item {DeckId = 1, ItemsId = 3, HardwareShortDesc = "Czujniki IoT (Internet of Things)", HardwareLongDesc = "Czujniki IoT zbierają dane z maszyn i procesów produkcyjnych, które następnie są przesyłane do systemów centralnych w celu analizy i monitorowania. Czujniki te mogą mierzyć różne parametry, takie jak temperatura, ciśnienie, wilgotność, wibracje, poziom hałasu itp.Zastosowanie: Zbieranie danych o stanie maszyn, monitorowanie warunków pracy, predykcyjne utrzymanie ruchu.", ItemsBaseCost = 0.5, ItemsCostWeight = 1 },
            new Item {DeckId = 1, ItemsId = 4, HardwareShortDesc = "Roboty przemysłowe", HardwareLongDesc = "Roboty przemysłowe wykonują zautomatyzowane zadania, takie jak montaż, spawanie, malowanie, pakowanie, i inne. Są niezbędne w procesie automatyzacji i mogą pracować w środowiskach wymagających precyzji i powtarzalności.Zastosowanie: Automatyzacja procesów produkcyjnych, redukcja kosztów pracy, poprawa jakości produktów.", ItemsBaseCost = 1.0, ItemsCostWeight = 1 },
            new Item {DeckId = 1, ItemsId = 5, HardwareShortDesc = "Wyświetlacze do systemów SCADA", HardwareLongDesc = "ADA to systemy nadzoru i zbierania danych, które monitorują i kontrolują procesy przemysłowe. SCADA integruje dane z różnych czujników i urządzeń, umożliwiając kompleksowe zarządzanie produkcją w czasie rzeczywistym.Zastosowanie: Monitorowanie procesów produkcyjnych, zarządzanie energią, zdalne sterowanie i diagnostyka.", ItemsBaseCost = 0.5, ItemsCostWeight = 1 },
            new Item {DeckId = 1, ItemsId = 6, HardwareShortDesc = "Komputery przemysłowe", HardwareLongDesc = "Komputery przemysłowe są bardziej wytrzymałe i przystosowane do pracy w trudnych warunkach produkcyjnych, takich jak wysokie temperatury, zapylenie, wibracje. Używane są do zarządzania procesami, analizowania danych i sterowania maszynami.Zastosowanie: Kontrola procesów, zbieranie i analiza danych produkcyjnych, integracja z systemami ERP/MES.", ItemsBaseCost = 0.5, ItemsCostWeight = 1 },
            new Item {DeckId = 1, ItemsId = 7, HardwareShortDesc = "Systemy RFID (Radio-Frequency Identification)", HardwareLongDesc = "RFID używa fal radiowych do identyfikacji i śledzenia obiektów w procesie produkcji. Etykiety RFID mogą być umieszczane na produktach, materiałach lub pojemnikach, co pozwala na śledzenie ich w czasie rzeczywistym.Zastosowanie: Śledzenie produktów w łańcuchu dostaw, zarządzanie zapasami, automatyzacja logistyki wewnętrznej.", ItemsBaseCost = 0.1, ItemsCostWeight = 1 },
            new Item {DeckId = 1, ItemsId = 8, HardwareShortDesc = "Bramki RFID", HardwareLongDesc = "Bramki RFID to urządzenia do bezkontaktowego śledzenia przedmiotów lub osób. Składają się z anten i czytnika, który odczytuje dane z tagów RFID przechodzących przez bramkę. Są używane w logistyce, kontroli dostępu i monitorowaniu ruchu.", ItemsBaseCost = 0.1, ItemsCostWeight = 1 },
            new Item {DeckId = 1, ItemsId = 9, HardwareShortDesc = "Drukarki RFID", HardwareLongDesc = "Drukarki RFID drukują etykiety z chipami RFID i kodami kreskowymi. Pozwalają na personalizację etykiet oraz zapisywanie danych na tagach RFID, co jest przydatne w zarządzaniu zapasami i kontroli dostępu.", ItemsBaseCost = 0.1, ItemsCostWeight = 1 },
            new Item {DeckId = 1, ItemsId = 10, HardwareShortDesc = "Etykiety dual frequency RFID", HardwareLongDesc = "Etykiety dual frequency RFID obsługują dwie częstotliwości radiowe (np. 125 kHz i 915 MHz). Dzięki temu są kompatybilne z różnymi systemami RFID, oferując większą wszechstronność i elastyczność w śledzeniu przedmiotów.", ItemsBaseCost = 0.1, ItemsCostWeight = 1 },
            new Item {DeckId = 1, ItemsId = 11, HardwareShortDesc = "LED RFID", HardwareLongDesc = "LED RFID to tagi RFID wyposażone w diody LED, które mogą sygnalizować różne stany, takie jak aktywność lub status urządzenia. Wykorzystywane są w systemach monitorowania i zarządzania, gdzie wizualna informacja o stanie tagu może zwiększać efektywność i ułatwiać obsługę.", ItemsBaseCost = 0.1, ItemsCostWeight = 1 },
            new Item {DeckId = 1, ItemsId = 12, HardwareShortDesc = "Temperature indication RFID", HardwareLongDesc = "Tagi RFID z funkcją wskazywania temperatury monitorują i zapisują temperaturę w czasie rzeczywistym. Są przydatne w zarządzaniu łańcuchem chłodniczym i w aplikacjach wymagających ścisłej kontroli temperatury, takich jak transport i przechowywanie wrażliwych produktów.", ItemsBaseCost = 0.1, ItemsCostWeight = 1 },
            new Item {DeckId = 1, ItemsId = 13, HardwareShortDesc = "Drukarki 3D", HardwareLongDesc = "Drukarki 3D umożliwiają szybkie prototypowanie i produkcję elementów na miejscu. Mogą być wykorzystywane do produkcji narzędzi, części zamiennych, a także do wytwarzania gotowych produktów.Zastosowanie: Prototypowanie, produkcja części, personalizacja produktów.", ItemsBaseCost = 1.0, ItemsCostWeight = 1 },
            new Item {DeckId = 1, ItemsId = 14, HardwareShortDesc = "Urządzenia do analizy danych (serwery, chmura obliczeniowa)", HardwareLongDesc = "Serwery i chmura obliczeniowa są wykorzystywane do przechowywania, przetwarzania i analizowania dużych ilości danych generowanych na hali produkcyjnej. Umożliwiają skomplikowaną analitykę, sztuczną inteligencję oraz integrację z innymi systemami.Zastosowanie: Przechowywanie danych produkcyjnych, analiza Big Data, wsparcie dla AI i ML.Zastosowanie: Wsparcie operatorów, konserwacja i szkolenia, zdalna pomoc techniczna.", ItemsBaseCost = 1.5, ItemsCostWeight = 1 },
            new Item {DeckId = 1, ItemsId = 15, HardwareShortDesc = "Wearables", HardwareLongDesc = "Urządzenia ubieralne są używane do wsparcia pracowników, umożliwiając dostęp do instrukcji, monitorowanie w czasie rzeczywistym oraz zdalne wsparcie techniczne .Zastosowanie: Wsparcie operatorów, zdalna pomoc techniczna.", ItemsBaseCost = 0.5, ItemsCostWeight = 1 },
            new Item {DeckId = 1, ItemsId = 16, HardwareShortDesc = "Gogle AR/VR", HardwareLongDesc = "Gogle AR/VR można wykorzystać do szkolenia i edukacji, projektowania i prototypowania, wsparcia w procesie produkcji czy inspekcji i diagnostyce.", ItemsBaseCost = 0.5, ItemsCostWeight = 1 },
            new Item {DeckId = 1, ItemsId = 17, HardwareShortDesc = "AGV / AMR", HardwareLongDesc = "Samojezdne pojazdy transportowe używane w magazynach i fabrykach do automatycznego przemieszczania wyrobów gotowych lub surowców. Tranport jednostek logistycznych (paleta, wózki, pojemniki) z posadzki lub wysokości do 1 metra. Transport ze strefy buforowej do stanowiska produkcyjnego lub transport wewnątrz magazynowy.", ItemsBaseCost = 1.0, ItemsCostWeight = 1 },
            new Item {DeckId = 1, ItemsId = 18, HardwareShortDesc = "Kamery przemysłowe", HardwareLongDesc = "Kamery przemysłowe na produkcji są kluczowymi elementami systemów monitorowania i kontroli jakości w zakładach produkcyjnych. Wykorzystują różne technologie, takie jak wizja komputerowa, do analizy i inspekcji procesów produkcyjnych. Dzięki nim możliwe jest monitorowanie stanu maszyn, kontrola jakości produktów, wykrywanie defektów oraz optymalizacja procesów. Kamery te mogą obejmować funkcje takie jak rozpoznawanie obrazów, pomiar odległości, czy analiza w czasie rzeczywistym, co pozwala na szybkie reagowanie na problemy i zapewnia wysoką efektywność produkcji.", ItemsBaseCost = 0.5, ItemsCostWeight = 1 },
            new Item {DeckId = 1, ItemsId = 19, HardwareShortDesc = "Stacje bazowe 5G:", HardwareLongDesc = "To kluczowe urządzenia odpowiedzialne za zapewnienie łączności 5G w obszarze zakładu produkcyjnego. Stacje bazowe składają się z anten, nadajników i odbiorników, które tworzą sieć komórkową 5G.", ItemsBaseCost = 3.0, ItemsCostWeight = 1 },
            new Item {DeckId = 1, ItemsId = 20, HardwareShortDesc = "Modemy 5G", HardwareLongDesc = "Urządzenia te umożliwiają podłączenie maszyn i systemów do sieci 5G. Modemy konwertują sygnały 5G na dane, które mogą być używane przez różne urządzenia produkcyjne.", ItemsBaseCost = 3.0, ItemsCostWeight = 1 },
            new Item {DeckId = 1, ItemsId = 21, HardwareShortDesc = "Routery 5G", HardwareLongDesc = "Routery zarządzają ruchem danych w sieci 5G, łącząc urządzenia końcowe z siecią i zapewniając stabilne i szybkie połączenia. Mogą również obsługiwać lokalne sieci bezprzewodowe w obrębie zakładu.", ItemsBaseCost = 3.0, ItemsCostWeight = 1 },
            new Item {DeckId = 1, ItemsId = 22, HardwareShortDesc = "Anteny 5G", HardwareLongDesc = "Anteny montowane na stacjach bazowych i innych urządzeniach są niezbędne do odbierania i nadawania sygnałów 5G. Odpowiednia konfiguracja anten zapewnia optymalne pokrycie i wydajność sieci.", ItemsBaseCost = 3.0, ItemsCostWeight = 1 },
            new Item {DeckId = 1, ItemsId = 23, HardwareShortDesc = "Machine Execution System (MES)", HardwareLongDesc = "Systemy zarządzania produkcją, które monitorują i kontrolują procesy produkcyjne na poziomie operacyjnym.", ItemsBaseCost = 20.0, ItemsCostWeight = 1 },
            new Item {DeckId = 1, ItemsId = 24, HardwareShortDesc = "Computer Aided Design (CAD)", HardwareLongDesc = "CAD to system komputerowy służący do projektowania i rysowania w różnych dziedzinach, takich jak inżynieria, architektura czy projektowanie produktu. Oprogramowanie CAD pozwala na tworzenie precyzyjnych rysunków technicznych, modeli 3D oraz symulacji, co ułatwia projektowanie, analizowanie i optymalizowanie produktów przed ich wytworzeniem.", ItemsBaseCost = 8.0, ItemsCostWeight = 1 },
            new Item {DeckId = 1, ItemsId = 25, HardwareShortDesc = "Robotic Process Automationn (RPA)", HardwareLongDesc = "RPA to technologia automatyzacji procesów biznesowych, która wykorzystuje roboty programowe (boty) do wykonywania powtarzalnych i rutynowych zadań. RPA może zautomatyzować operacje takie jak wprowadzanie danych, generowanie raportów czy obsługa klienta, co zwiększa efektywność i redukuje błędy ludzkie.", ItemsBaseCost = 8.0, ItemsCostWeight = 1 },
            new Item {DeckId = 1, ItemsId = 26, HardwareShortDesc = "Production Planning (PP)", HardwareLongDesc = "Obejmuje zarządzanie harmonogramami produkcji, alokację zasobów, zarządzanie zapasami i koordynację działań w celu zapewnienia, że produkcja przebiega zgodnie z planem i jest optymalnie dostosowana do zapotrzebowania rynkowego.", ItemsBaseCost = 7.0, ItemsCostWeight = 1 },
            new Item {DeckId = 1, ItemsId = 27, HardwareShortDesc = "Quality Management (QM)", HardwareLongDesc = "QM to system zarządzania jakością, który zajmuje się kontrolowaniem i zapewnianiem wysokich standardów jakości w procesach produkcyjnych. System QM monitoruje jakość surowców, procesów produkcyjnych i gotowych produktów, aby zapewnić zgodność z normami i wymaganiami klientów oraz poprawiać jakość poprzez analizę danych i wdrażanie działań korygujących.", ItemsBaseCost = 6.0, ItemsCostWeight = 1 },
            new Item {DeckId = 1, ItemsId = 28, HardwareShortDesc = "Supervisory Control and Data Acquisition (SCADA)", HardwareLongDesc = "Systemy nadzoru i akwizycji danych, które są używane do monitorowania i sterowania procesami przemysłowymi w czasie rzeczywistym.", ItemsBaseCost = 12.0, ItemsCostWeight = 1 },
            new Item {DeckId = 1, ItemsId = 29, HardwareShortDesc = "Warehouse Management System (WMS)", HardwareLongDesc = "Systemy zarządzania magazynem, które optymalizują zarządzanie przestrzenią magazynową, kontrolą zapasów i operacjami logistycznymi.", ItemsBaseCost = 7.0, ItemsCostWeight = 1 },
            new Item {DeckId = 1, ItemsId = 30, HardwareShortDesc = "Product Lifecycle Management (PLM)", HardwareLongDesc = "Systemy zarządzania cyklem życia produktu, które integrują wszystkie informacje związane z projektem, produkcją, serwisem i wycofaniem produktów.", ItemsBaseCost = 12.0, ItemsCostWeight = 1 },
            new Item {DeckId = 1, ItemsId = 31, HardwareShortDesc = "Business Inteligence (BI)", HardwareLongDesc = "Systemy do analizy danych biznesowych, które pomagają w podejmowaniu decyzji na podstawie zgromadzonych danych.", ItemsBaseCost = 7.0, ItemsCostWeight = 1 },
            new Item {DeckId = 1, ItemsId = 32, HardwareShortDesc = "CRM (Customer Relationship Management)", HardwareLongDesc = "Systemy do zarządzania relacjami z klientami, które pomagają w organizacji, automatyzacji i synchronizacji sprzedaży, marketingu, obsługi klienta.", ItemsBaseCost = 8.0, ItemsCostWeight = 1 },
            new Item {DeckId = 1, ItemsId = 33, HardwareShortDesc = "SCM (Supply Chain Management)", HardwareLongDesc = "Systemy zarządzania łańcuchem dostaw, które pomagają w zarządzaniu przepływem towarów, informacji i finansów w procesie produkcji i dystrybucji.", ItemsBaseCost = 8.0, ItemsCostWeight = 1 },
            new Item {DeckId = 1, ItemsId = 34, HardwareShortDesc = "HCM (Human Capital Management)", HardwareLongDesc = "Systemy zarządzania kapitałem ludzkim, które obejmują procesy zarządzania personelem, w tym rekrutację, szkolenia, wynagrodzenia i zarządzanie talentami.", ItemsBaseCost = 8.0, ItemsCostWeight = 1 },
            new Item {DeckId = 1, ItemsId = 35, HardwareShortDesc = "TMS (Transportation Management System)", HardwareLongDesc = "Systemy zarządzania transportem, które pomagają w planowaniu, realizacji i optymalizacji transportu towarów.", ItemsBaseCost = 8.0, ItemsCostWeight = 1 },
        };
        
        foreach (var newItem in items)
        {
            var existingItem = context.Items.FirstOrDefault(u => u.ItemsId == newItem.ItemsId);
            if (existingItem != null)
            {
                // Aktualizacja danych przedmiotów
                existingItem.CardId = newItem.CardId;
                existingItem.HardwareShortDesc = newItem.HardwareShortDesc;
                existingItem.HardwareLongDesc= newItem.HardwareLongDesc;
                existingItem.ItemsBaseCost = newItem.ItemsBaseCost;
            }
            else
            {
                // Dodanie nowego przedmiotu
                context.Items.Add(newItem);
            }
        }
        context.SaveChanges();
        Console.WriteLine("Zaktualizowano / dodano Przedmioty do bazy MySQL!");
    }
}
